name: Monitoramento ANEEL

on:
  schedule:
    - cron: '0 8 * * *'  # rodar diariamente às 08h00 UTC-3
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repositório
      uses: actions/checkout@v4

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install playwright
        playwright install

    - name: Executar scraper
      run: python scraper_aneel_free.py

    - name: Upload arquivos de debug e resultados
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: arquivos-monitoramento-aneel
        path: |
          pagina_debug.html
          resultado_Portaria.html
          resultados_aneel.json
